server:
  port: 3000
spring:
  application:
    name: product-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:123456@localhost:3002/eureka
  instance:
    prefer-ip-address: true #显示IP